<template>
  <GameMain :game="game" :orientation="parsedGame[0].headers.get('White') === 'flys1ck' ? 'white' : 'black'" />
</template>

<script setup lang="ts">
import GameMain from "@/components/GameMain.vue";
import { useGame } from "@/composables/useGame";
import { useBreadcrumbs } from "@/stores/useBreadcrumbs";
import { useChessDotCom } from "@/stores/useChessDotCom";
import { AcademicCapIcon } from "@heroicons/vue/24/solid";
import { parsePgn } from "chessops/pgn";
import { definePage, useRoute } from "vue-router/auto";

const route = useRoute("/games/chessdotcom/[gameId]");
const chessDotCom = useChessDotCom();
// assuming the route guard will prevent the access of uncached games
const gameInfo = (await chessDotCom.client.getGameByUuid(route.params.gameId))!;

const game = useGame();
game.tree.fromPgn(gameInfo.pgn);
const parsedGame = parsePgn(gameInfo.pgn);
const { setBreadcrumbs } = useBreadcrumbs();
setBreadcrumbs([
  {
    icon: AcademicCapIcon,
    name: "Games",
    to: "/games/",
  },
  {
    name: "Chess.com",
    to: "/games/chessdotcom/",
  },
  {
    name: `${parsedGame[0].headers.get("White")} vs. ${parsedGame[0].headers.get("Black")}`,
    to: `/games/chessdotcom/${route.params.gameId}`,
  },
]);

definePage({
  meta: {
    layout: "breadcrumbs",
  },
  // @ts-ignore types are generated by vue router
  beforeEnter: async (to, from, next) => {
    // prevent entering page, if it's not done through the game list
    // chess.com api does not allow fetching games directly
    if (from.name !== "/games/chessdotcom/") next("/games/chessdotcom/");
    else next();
  },
});
</script>
