/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Chapters {
  created_at: Generated<string>;
  id: Generated<number>;
  name: string;
  study: number;
}

export interface ChessPositions {
  id: Generated<number>;
  position_key: string;
}

export interface Lines {
  chapter: number;
  created_at: Generated<string>;
  id: Generated<number>;
  moves: string;
  name: string;
  orientation: Generated<string>;
  pgn: string;
}

export interface Positions {
  chess_position: number;
  created_at: Generated<string>;
  destination: Generated<string>;
  fullmove_number: number;
  halfmove_clock: number;
  id: Generated<number>;
  line: number;
  ply: number;
  san: string;
  source: Generated<string>;
}

export interface Settings {
  key: string;
  value: string;
}

export interface Studies {
  created_at: Generated<string>;
  description: string | null;
  id: Generated<number>;
  name: string;
}

export interface DB {
  chapters: Chapters;
  chess_positions: ChessPositions;
  lines: Lines;
  positions: Positions;
  settings: Settings;
  studies: Studies;
}
