/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/analysis/': RouteRecordInfo<
      '/analysis/',
      '/analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games/': RouteRecordInfo<
      '/games/',
      '/games',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games/chessdotcom/': RouteRecordInfo<
      '/games/chessdotcom/',
      '/games/chessdotcom',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games/chessdotcom/[gameId]': RouteRecordInfo<
      '/games/chessdotcom/[gameId]',
      '/games/chessdotcom/:gameId',
      { gameId: ParamValue<true> },
      { gameId: ParamValue<false> },
      | never
    >,
    '/games/lichess/': RouteRecordInfo<
      '/games/lichess/',
      '/games/lichess',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games/lichess/[gameId]': RouteRecordInfo<
      '/games/lichess/[gameId]',
      '/games/lichess/:gameId',
      { gameId: ParamValue<true> },
      { gameId: ParamValue<false> },
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/studies/': RouteRecordInfo<
      '/studies/',
      '/studies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/studies/[studyId]/': RouteRecordInfo<
      '/studies/[studyId]/',
      '/studies/:studyId',
      { studyId: ParamValue<true> },
      { studyId: ParamValue<false> },
      | never
    >,
    '/studies/[studyId]/chapters/[chapterId]/': RouteRecordInfo<
      '/studies/[studyId]/chapters/[chapterId]/',
      '/studies/:studyId/chapters/:chapterId',
      { studyId: ParamValue<true>, chapterId: ParamValue<true> },
      { studyId: ParamValue<false>, chapterId: ParamValue<false> },
      | never
    >,
    '/studies/[studyId]/chapters/[chapterId]/lines/[lineId]': RouteRecordInfo<
      '/studies/[studyId]/chapters/[chapterId]/lines/[lineId]',
      '/studies/:studyId/chapters/:chapterId/lines/:lineId',
      { studyId: ParamValue<true>, chapterId: ParamValue<true>, lineId: ParamValue<true> },
      { studyId: ParamValue<false>, chapterId: ParamValue<false>, lineId: ParamValue<false> },
      | never
    >,
    '/studies/[studyId]/chapters/new': RouteRecordInfo<
      '/studies/[studyId]/chapters/new',
      '/studies/:studyId/chapters/new',
      { studyId: ParamValue<true> },
      { studyId: ParamValue<false> },
      | never
    >,
    '/studies/[studyId]/edit': RouteRecordInfo<
      '/studies/[studyId]/edit',
      '/studies/:studyId/edit',
      { studyId: ParamValue<true> },
      { studyId: ParamValue<false> },
      | never
    >,
    '/studies/new': RouteRecordInfo<
      '/studies/new',
      '/studies/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/analysis/index.vue': {
      routes:
        | '/analysis/'
      views:
        | never
    }
    'src/pages/games/index.vue': {
      routes:
        | '/games/'
      views:
        | never
    }
    'src/pages/games/chessdotcom/index.vue': {
      routes:
        | '/games/chessdotcom/'
      views:
        | never
    }
    'src/pages/games/chessdotcom/[gameId].vue': {
      routes:
        | '/games/chessdotcom/[gameId]'
      views:
        | never
    }
    'src/pages/games/lichess/index.vue': {
      routes:
        | '/games/lichess/'
      views:
        | never
    }
    'src/pages/games/lichess/[gameId].vue': {
      routes:
        | '/games/lichess/[gameId]'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/studies/index.vue': {
      routes:
        | '/studies/'
      views:
        | never
    }
    'src/pages/studies/[studyId]/index.vue': {
      routes:
        | '/studies/[studyId]/'
      views:
        | never
    }
    'src/pages/studies/[studyId]/chapters/[chapterId]/index.vue': {
      routes:
        | '/studies/[studyId]/chapters/[chapterId]/'
      views:
        | never
    }
    'src/pages/studies/[studyId]/chapters/[chapterId]/lines/[lineId].vue': {
      routes:
        | '/studies/[studyId]/chapters/[chapterId]/lines/[lineId]'
      views:
        | never
    }
    'src/pages/studies/[studyId]/chapters/new.vue': {
      routes:
        | '/studies/[studyId]/chapters/new'
      views:
        | never
    }
    'src/pages/studies/[studyId]/edit.vue': {
      routes:
        | '/studies/[studyId]/edit'
      views:
        | never
    }
    'src/pages/studies/new.vue': {
      routes:
        | '/studies/new'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
