name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: main

env:
  STOCKFISH_VERSION: 18

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - platform: "ubuntu-22.04"
            arch: "x86_64"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - uses: oven-sh/setup-bun@v2
        name: Install Bun

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - run: bun install

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev webkit2gtk-driver xvfb

      - uses: actions/cache@v5
        id: stockfish-cache
        with:
          path: |
            external/stockfish
          key: stockfish-${{ env.STOCKFISH_VERSION }}-${{ matrix.platform }}-${{ matrix.arch }}

      - name: Install Stockfish
        run: bun run scripts/downloadStockfish.ts
        if: steps.stockfish-cache.outputs.cache-hit != 'true'

      - name: Generate Target Triple
        run: |
          mkdir src-tauri/bin
          bun run scripts/generateTargetTriple.ts

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
