name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: pnpm install

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - uses: actions/cache@v3
        id: stockfish-cache
        with:
          path: |
            external/stockfish
          key: stockfish-${{ env.STOCKFISH_VERSION }}-ubuntu-latest
        env:
          STOCKFISH_VERSION: 16

      - name: Install Stockfish
        run: node scripts/downloadStockfish.js
        if: steps.stockfish-cache.outputs.cache-hit != 'true'

      - name: Generate Target Triple
        run: |
          mkdir src-tauri/bin
          node scripts/generateTargetTriple.js

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
