name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    # Open questions
    # - Rust version is not pinned @setup/cargo?

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - run: echo "PGN_EXTRACT_VERSION=22-11" >> $GITHUB_ENV

      - uses: actions/cache@v3
        id: pgn-extract-cache
        with:
          path: |
            external/
          key: pgn-extract-${{ env.PGN_EXTRACT_VERSION }}

      - name: Install pgn-extract
        run: make pgn-extract
        if: steps.pgn-extract-cache.outputs.cache-hit != 'true'
        env:
          PGN_EXTRACT_VERSION: ${{ env.PGN_EXTRACT_VERSION }}

      # - name: Mock bundled binaries
      #   run: |
      #     mkdir external
      #     mkdir -p src-tauri/bin
      #     touch external/stockfish
      #     touch external/pgn-extract
      #     node scripts/generateTargetTriple.js

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target

      - name: Build application
        run: pnpm tauri build
