name: Release

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install OS dependencies
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install frontend dependencies
        run: pnpm install

      - uses: actions/cache@v3
        id: stockfish-cache
        with:
          path: |
            external/stockfish
          key: stockfish-${{ env.STOCKFISH_VERSION }}-${{ matrix.platform }}
        env:
          STOCKFISH_VERSION: 16

      - name: Install Stockfish
        run: node scripts/downloadStockfish.js
        if: steps.stockfish-cache.outputs.cache-hit != 'true'

      - name: Generate Target Triples
        run: |
          mkdir src-tauri/bin
          node scripts/generateTargetTriple.js

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: OpenChess v__VERSION__
          releaseDraft: true
          prerelease: false
