name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: oven-sh/setup-bun@v2
        name: Install bun

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install OS dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev webkit2gtk-driver xvfb

      - name: Install node-gyp dependencies
        if: startsWith(matrix.platform, 'macos')
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install frontend dependencies
        run: bun install

      - uses: actions/cache@v5
        id: stockfish-cache
        with:
          path: |
            external/stockfish
          key: stockfish-${{ env.STOCKFISH_VERSION }}-${{ matrix.platform }}
        env:
          STOCKFISH_VERSION: 16

      - name: Install Stockfish
        run: bun run scripts/downloadStockfish.ts
        if: steps.stockfish-cache.outputs.cache-hit != 'true'

      - name: Generate Target Triples
        run: |
          mkdir src-tauri/bin
          bun run scripts/generateTargetTriple.ts

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: OpenChess v__VERSION__
          releaseDraft: true
          prerelease: false
